In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("women.csv")

In [3]:
df

,Industry,May_2020,Mar_2021,Apr_2021,May_2021,pct_May_2020,pct_Mar_2021,pct_Apr_2021,pct_May_2021
0,Total nonfarm,65348.0,71634.0,71821.0,72135.0,49.1,49.7,49.8,49.8
1,Total private,53135.0,59242.0,59375.0,59647.0,47.6,48.4,48.4,48.4
2,Goods-producing,4308.0,4619.0,4621.0,4637.0,22.4,22.7,22.7,22.8
3,Mining and logging,88.0,85.0,84.0,89.0,14.6,13.9,13.7,14.5
4,Construction,932.0,999.0,1006.0,1013.0,13.3,13.4,13.5,13.6
5,Manufacturing,3288.0,3535.0,3531.0,3535.0,28.2,28.7,28.8,28.8
6,Durable goods,1724.0,1866.0,1865.0,1873.0,23.9,24.4,24.5,24.6
7,Nondurable goods,1564.0,1669.0,1666.0,1662.0,35.1,35.8,35.7,35.6
8,Private service-providing,48827.0,54623.0,54754.0,55010.0,52.8,53.5,53.5,53.5
9,"Trade, transportation, and utilities",9529.0,10686.0,10651.0,10660.0,38.2,39.3,39.3,39.3
10,Wholesale trade,1626.9,1696.7,1700.9,1714.4,29.5,30.0,30.0,30.2
11,Retail trade,6493.6,7390.8,7366.8,7357.3,47.6,48.5,48.5,48.4
12,Transportation and warehousing,1275.3,1465.0,1448.8,1453.7,24.3,25.5,25.4,25.4
13,Utilities,132.9,133.8,134.3,134.2,24.5,24.8,24.9,24.8
14,Information,1031.0,1066.0,1074.0,1076.0,39.7,39.7,39.9,39.5
15,Financial activities,4868.0,4963.0,4963.0,4932.0,56.5,56.5,56.4,56.0
16,Professional and business services,8712.0,9600.0,9569.0,9582.0,45.3,46.1,46.2,46.2
17,Education and health services,16980.0,18047.0,18082.0,18155.0,76.8,77.1,77.2,77.2
18,Leisure and hospitality,5285.0,7323.0,7467.0,7639.0,52.1,53.2,53.0,53.1
19,Other services,2422.0,2938.0,2948.0,2966.0,50.7,53.0,52.9,53.1
20,Government,12213.0,12392.0,12446.0,12488.0,57.3,57.5,57.6,57.6

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Industry      21 non-null     object
 1   May_2020      21 non-null     float64
 2   Mar_2021      21 non-null     float64
 3   Apr_2021      21 non-null     float64
 4   May_2021      21 non-null     float64
 5   pct_May_2020  21 non-null     float64
 6   pct_Mar_2021  21 non-null     float64
 7   pct_Apr_2021  21 non-null     float64
 8   pct_May_2021  21 non-null     float64
dtypes: float64(8), object(1)
memory usage: 1.6+ KB

In [7]:
df.May_2021-df.May_2020

0     6787.0
1     6512.0
2      329.0
3        1.0
4       81.0
5      247.0
6      149.0
7       98.0
8     6183.0
9     1131.0
10      87.5
11     863.7
12     178.4
13       1.3
14      45.0
15      64.0
16     870.0
17    1175.0
18    2354.0
19     544.0
20     275.0
dtype: float64

In [8]:
df['may_diff_yearly']=df.May_2021-df.May_2020

In [9]:
df

,Industry,May_2020,Mar_2021,Apr_2021,May_2021,pct_May_2020,pct_Mar_2021,pct_Apr_2021,pct_May_2021,may_diff_yearly
0,Total nonfarm,65348.0,71634.0,71821.0,72135.0,49.1,49.7,49.8,49.8,6787.0
1,Total private,53135.0,59242.0,59375.0,59647.0,47.6,48.4,48.4,48.4,6512.0
2,Goods-producing,4308.0,4619.0,4621.0,4637.0,22.4,22.7,22.7,22.8,329.0
3,Mining and logging,88.0,85.0,84.0,89.0,14.6,13.9,13.7,14.5,1.0
4,Construction,932.0,999.0,1006.0,1013.0,13.3,13.4,13.5,13.6,81.0
5,Manufacturing,3288.0,3535.0,3531.0,3535.0,28.2,28.7,28.8,28.8,247.0
6,Durable goods,1724.0,1866.0,1865.0,1873.0,23.9,24.4,24.5,24.6,149.0
7,Nondurable goods,1564.0,1669.0,1666.0,1662.0,35.1,35.8,35.7,35.6,98.0
8,Private service-providing,48827.0,54623.0,54754.0,55010.0,52.8,53.5,53.5,53.5,6183.0
9,"Trade, transportation, and utilities",9529.0,10686.0,10651.0,10660.0,38.2,39.3,39.3,39.3,1131.0
10,Wholesale trade,1626.9,1696.7,1700.9,1714.4,29.5,30.0,30.0,30.2,87.5
11,Retail trade,6493.6,7390.8,7366.8,7357.3,47.6,48.5,48.5,48.4,863.7
12,Transportation and warehousing,1275.3,1465.0,1448.8,1453.7,24.3,25.5,25.4,25.4,178.4
13,Utilities,132.9,133.8,134.3,134.2,24.5,24.8,24.9,24.8,1.3
14,Information,1031.0,1066.0,1074.0,1076.0,39.7,39.7,39.9,39.5,45.0
15,Financial activities,4868.0,4963.0,4963.0,4932.0,56.5,56.5,56.4,56.0,64.0
16,Professional and business services,8712.0,9600.0,9569.0,9582.0,45.3,46.1,46.2,46.2,870.0
17,Education and health services,16980.0,18047.0,18082.0,18155.0,76.8,77.1,77.2,77.2,1175.0
18,Leisure and hospitality,5285.0,7323.0,7467.0,7639.0,52.1,53.2,53.0,53.1,2354.0
19,Other services,2422.0,2938.0,2948.0,2966.0,50.7,53.0,52.9,53.1,544.0
20,Government,12213.0,12392.0,12446.0,12488.0,57.3,57.5,57.6,57.6,275.0

In [16]:
df['pct_may_diff_yearly']=(df.may_diff_yearly*100/df.May_2020).round()

In [15]:
df

,Industry,May_2020,Mar_2021,Apr_2021,May_2021,pct_May_2020,pct_Mar_2021,pct_Apr_2021,pct_May_2021,may_diff_yearly,pct_may_diff_yearly
0,Total nonfarm,65348.0,71634.0,71821.0,72135.0,49.1,49.7,49.8,49.8,6787.0,10.0
1,Total private,53135.0,59242.0,59375.0,59647.0,47.6,48.4,48.4,48.4,6512.0,12.0
2,Goods-producing,4308.0,4619.0,4621.0,4637.0,22.4,22.7,22.7,22.8,329.0,8.0
3,Mining and logging,88.0,85.0,84.0,89.0,14.6,13.9,13.7,14.5,1.0,1.0
4,Construction,932.0,999.0,1006.0,1013.0,13.3,13.4,13.5,13.6,81.0,9.0
5,Manufacturing,3288.0,3535.0,3531.0,3535.0,28.2,28.7,28.8,28.8,247.0,8.0
6,Durable goods,1724.0,1866.0,1865.0,1873.0,23.9,24.4,24.5,24.6,149.0,9.0
7,Nondurable goods,1564.0,1669.0,1666.0,1662.0,35.1,35.8,35.7,35.6,98.0,6.0
8,Private service-providing,48827.0,54623.0,54754.0,55010.0,52.8,53.5,53.5,53.5,6183.0,13.0
9,"Trade, transportation, and utilities",9529.0,10686.0,10651.0,10660.0,38.2,39.3,39.3,39.3,1131.0,12.0
10,Wholesale trade,1626.9,1696.7,1700.9,1714.4,29.5,30.0,30.0,30.2,87.5,5.0
11,Retail trade,6493.6,7390.8,7366.8,7357.3,47.6,48.5,48.5,48.4,863.7,13.0
12,Transportation and warehousing,1275.3,1465.0,1448.8,1453.7,24.3,25.5,25.4,25.4,178.4,14.0
13,Utilities,132.9,133.8,134.3,134.2,24.5,24.8,24.9,24.8,1.3,1.0
14,Information,1031.0,1066.0,1074.0,1076.0,39.7,39.7,39.9,39.5,45.0,4.0
15,Financial activities,4868.0,4963.0,4963.0,4932.0,56.5,56.5,56.4,56.0,64.0,1.0
16,Professional and business services,8712.0,9600.0,9569.0,9582.0,45.3,46.1,46.2,46.2,870.0,10.0
17,Education and health services,16980.0,18047.0,18082.0,18155.0,76.8,77.1,77.2,77.2,1175.0,7.0
18,Leisure and hospitality,5285.0,7323.0,7467.0,7639.0,52.1,53.2,53.0,53.1,2354.0,45.0
19,Other services,2422.0,2938.0,2948.0,2966.0,50.7,53.0,52.9,53.1,544.0,22.0
20,Government,12213.0,12392.0,12446.0,12488.0,57.3,57.5,57.6,57.6,275.0,2.0

In [18]:
df.sort_values(by='pct_may_diff_yearly', ascending=False)

,Industry,May_2020,Mar_2021,Apr_2021,May_2021,pct_May_2020,pct_Mar_2021,pct_Apr_2021,pct_May_2021,may_diff_yearly,pct_may_diff_yearly
18,Leisure and hospitality,5285.0,7323.0,7467.0,7639.0,52.1,53.2,53.0,53.1,2354.0,45.0
19,Other services,2422.0,2938.0,2948.0,2966.0,50.7,53.0,52.9,53.1,544.0,22.0
12,Transportation and warehousing,1275.3,1465.0,1448.8,1453.7,24.3,25.5,25.4,25.4,178.4,14.0
8,Private service-providing,48827.0,54623.0,54754.0,55010.0,52.8,53.5,53.5,53.5,6183.0,13.0
11,Retail trade,6493.6,7390.8,7366.8,7357.3,47.6,48.5,48.5,48.4,863.7,13.0
9,"Trade, transportation, and utilities",9529.0,10686.0,10651.0,10660.0,38.2,39.3,39.3,39.3,1131.0,12.0
1,Total private,53135.0,59242.0,59375.0,59647.0,47.6,48.4,48.4,48.4,6512.0,12.0
0,Total nonfarm,65348.0,71634.0,71821.0,72135.0,49.1,49.7,49.8,49.8,6787.0,10.0
16,Professional and business services,8712.0,9600.0,9569.0,9582.0,45.3,46.1,46.2,46.2,870.0,10.0
4,Construction,932.0,999.0,1006.0,1013.0,13.3,13.4,13.5,13.6,81.0,9.0
6,Durable goods,1724.0,1866.0,1865.0,1873.0,23.9,24.4,24.5,24.6,149.0,9.0
2,Goods-producing,4308.0,4619.0,4621.0,4637.0,22.4,22.7,22.7,22.8,329.0,8.0
5,Manufacturing,3288.0,3535.0,3531.0,3535.0,28.2,28.7,28.8,28.8,247.0,8.0
17,Education and health services,16980.0,18047.0,18082.0,18155.0,76.8,77.1,77.2,77.2,1175.0,7.0
7,Nondurable goods,1564.0,1669.0,1666.0,1662.0,35.1,35.8,35.7,35.6,98.0,6.0
10,Wholesale trade,1626.9,1696.7,1700.9,1714.4,29.5,30.0,30.0,30.2,87.5,5.0
14,Information,1031.0,1066.0,1074.0,1076.0,39.7,39.7,39.9,39.5,45.0,4.0
20,Government,12213.0,12392.0,12446.0,12488.0,57.3,57.5,57.6,57.6,275.0,2.0
15,Financial activities,4868.0,4963.0,4963.0,4932.0,56.5,56.5,56.4,56.0,64.0,1.0
13,Utilities,132.9,133.8,134.3,134.2,24.5,24.8,24.9,24.8,1.3,1.0
3,Mining and logging,88.0,85.0,84.0,89.0,14.6,13.9,13.7,14.5,1.0,1.0

In [19]:
df['gender_may_diff_yearly']=df.pct_May_2021-df.pct_May_2020

In [23]:
df.sort_values(by='gender_may_diff_yearly', ascending=False)

,Industry,May_2020,Mar_2021,Apr_2021,May_2021,pct_May_2020,pct_Mar_2021,pct_Apr_2021,pct_May_2021,may_diff_yearly,pct_may_diff_yearly,gender_may_diff_yearly
19,Other services,2422.0,2938.0,2948.0,2966.0,50.7,53.0,52.9,53.1,544.0,22.0,2.4
12,Transportation and warehousing,1275.3,1465.0,1448.8,1453.7,24.3,25.5,25.4,25.4,178.4,14.0,1.1
9,"Trade, transportation, and utilities",9529.0,10686.0,10651.0,10660.0,38.2,39.3,39.3,39.3,1131.0,12.0,1.1
18,Leisure and hospitality,5285.0,7323.0,7467.0,7639.0,52.1,53.2,53.0,53.1,2354.0,45.0,1.0
16,Professional and business services,8712.0,9600.0,9569.0,9582.0,45.3,46.1,46.2,46.2,870.0,10.0,0.9
1,Total private,53135.0,59242.0,59375.0,59647.0,47.6,48.4,48.4,48.4,6512.0,12.0,0.8
11,Retail trade,6493.6,7390.8,7366.8,7357.3,47.6,48.5,48.5,48.4,863.7,13.0,0.8
6,Durable goods,1724.0,1866.0,1865.0,1873.0,23.9,24.4,24.5,24.6,149.0,9.0,0.7
8,Private service-providing,48827.0,54623.0,54754.0,55010.0,52.8,53.5,53.5,53.5,6183.0,13.0,0.7
10,Wholesale trade,1626.9,1696.7,1700.9,1714.4,29.5,30.0,30.0,30.2,87.5,5.0,0.7
0,Total nonfarm,65348.0,71634.0,71821.0,72135.0,49.1,49.7,49.8,49.8,6787.0,10.0,0.7
5,Manufacturing,3288.0,3535.0,3531.0,3535.0,28.2,28.7,28.8,28.8,247.0,8.0,0.6
7,Nondurable goods,1564.0,1669.0,1666.0,1662.0,35.1,35.8,35.7,35.6,98.0,6.0,0.5
17,Education and health services,16980.0,18047.0,18082.0,18155.0,76.8,77.1,77.2,77.2,1175.0,7.0,0.4
2,Goods-producing,4308.0,4619.0,4621.0,4637.0,22.4,22.7,22.7,22.8,329.0,8.0,0.4
20,Government,12213.0,12392.0,12446.0,12488.0,57.3,57.5,57.6,57.6,275.0,2.0,0.3
13,Utilities,132.9,133.8,134.3,134.2,24.5,24.8,24.9,24.8,1.3,1.0,0.3
4,Construction,932.0,999.0,1006.0,1013.0,13.3,13.4,13.5,13.6,81.0,9.0,0.3
3,Mining and logging,88.0,85.0,84.0,89.0,14.6,13.9,13.7,14.5,1.0,1.0,-0.1
14,Information,1031.0,1066.0,1074.0,1076.0,39.7,39.7,39.9,39.5,45.0,4.0,-0.2
15,Financial activities,4868.0,4963.0,4963.0,4932.0,56.5,56.5,56.4,56.0,64.0,1.0,-0.5

In [36]:
df['males']=100-df.pct_May_2021

In [39]:
df.sort_values(by='pct_may_diff_yearly', ascending=False)

,Industry,May_2020,Mar_2021,Apr_2021,May_2021,pct_May_2020,pct_Mar_2021,pct_Apr_2021,pct_May_2021,may_diff_yearly,pct_may_diff_yearly,gender_may_diff_yearly,males
18,Leisure and hospitality,5285.0,7323.0,7467.0,7639.0,52.1,53.2,53.0,53.1,2354.0,45.0,1.0,46.9
19,Other services,2422.0,2938.0,2948.0,2966.0,50.7,53.0,52.9,53.1,544.0,22.0,2.4,46.9
12,Transportation and warehousing,1275.3,1465.0,1448.8,1453.7,24.3,25.5,25.4,25.4,178.4,14.0,1.1,74.6
8,Private service-providing,48827.0,54623.0,54754.0,55010.0,52.8,53.5,53.5,53.5,6183.0,13.0,0.7,46.5
11,Retail trade,6493.6,7390.8,7366.8,7357.3,47.6,48.5,48.5,48.4,863.7,13.0,0.8,51.6
9,"Trade, transportation, and utilities",9529.0,10686.0,10651.0,10660.0,38.2,39.3,39.3,39.3,1131.0,12.0,1.1,60.7
1,Total private,53135.0,59242.0,59375.0,59647.0,47.6,48.4,48.4,48.4,6512.0,12.0,0.8,51.6
0,Total nonfarm,65348.0,71634.0,71821.0,72135.0,49.1,49.7,49.8,49.8,6787.0,10.0,0.7,50.2
16,Professional and business services,8712.0,9600.0,9569.0,9582.0,45.3,46.1,46.2,46.2,870.0,10.0,0.9,53.8
4,Construction,932.0,999.0,1006.0,1013.0,13.3,13.4,13.5,13.6,81.0,9.0,0.3,86.4
6,Durable goods,1724.0,1866.0,1865.0,1873.0,23.9,24.4,24.5,24.6,149.0,9.0,0.7,75.4
2,Goods-producing,4308.0,4619.0,4621.0,4637.0,22.4,22.7,22.7,22.8,329.0,8.0,0.4,77.2
5,Manufacturing,3288.0,3535.0,3531.0,3535.0,28.2,28.7,28.8,28.8,247.0,8.0,0.6,71.2
17,Education and health services,16980.0,18047.0,18082.0,18155.0,76.8,77.1,77.2,77.2,1175.0,7.0,0.4,22.8
7,Nondurable goods,1564.0,1669.0,1666.0,1662.0,35.1,35.8,35.7,35.6,98.0,6.0,0.5,64.4
10,Wholesale trade,1626.9,1696.7,1700.9,1714.4,29.5,30.0,30.0,30.2,87.5,5.0,0.7,69.8
14,Information,1031.0,1066.0,1074.0,1076.0,39.7,39.7,39.9,39.5,45.0,4.0,-0.2,60.5
20,Government,12213.0,12392.0,12446.0,12488.0,57.3,57.5,57.6,57.6,275.0,2.0,0.3,42.4
15,Financial activities,4868.0,4963.0,4963.0,4932.0,56.5,56.5,56.4,56.0,64.0,1.0,-0.5,44.0
13,Utilities,132.9,133.8,134.3,134.2,24.5,24.8,24.9,24.8,1.3,1.0,0.3,75.2
3,Mining and logging,88.0,85.0,84.0,89.0,14.6,13.9,13.7,14.5,1.0,1.0,-0.1,85.5